spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/taskDictionary
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db/changelog/changeLog.xml'

  hazelcast:
    config: classpath:hazelcast-client.yaml
  cache:
    type: hazelcast

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir.taskDictionary