spring:
  application:
    name: PayService
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  main:
    banner-mode: 'off'

  datasource:
    url: jdbc:postgresql://localhost:5432/payService
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8802

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true